### PR TITLE
Fix automatic merge workflow actor check.

### PR DESCRIPTION
**Pull request by houcros**
Pipelines are skipping this step, e.g. https://github.com/moia-oss/scynamo/pull/437.
And I can only imagine it's because the actor check is wrong. It worked with my own
handle before.

### CODE REVIEW

**Comment by m-dobler** [comment]
I would have expected that the skip is due to the workflow only starting for a PR being created and those PRs were already created 🤔 Maybe next Monday we'd see if it's working for new PRs

**Comment by houcros** [comment]
Mmh yes, could be that also... Although the workflow did run, but maybe the `actor` was not set anymore... It's mostly a guessing game :( We can wait till Monday to be sure.

**Comment by m-dobler** [comment]
I triggered the scala-steward workflow also now manually, maybe there is a new dynamo update already, it's possible that they have daily releases. Otherwise we'll see on Monday 🤷‍♂️

**Comment by houcros** [comment]
But it seems to me the handle for the bot is `scala-steward-for-moia` because the URL points to https://github.com/apps/scala-steward-for-moia ... But I don't actually know, it's just it looks more reasonable...

**Comment by m-dobler** [comment]
Worked for the new PR https://github.com/moia-oss/scynamo/pull/449

**Comment by houcros** [comment]
Sweet! This is not needed then :) Closing.

**Pull request closed without merging**
