### PR TITLE
Add some codeowners and delete some others.

### PR DESCRIPTION
**Pull request by houcros**

### CODE REVIEW

**Review by m-dobler — APPROVED** [review]

**Review by saeltz — COMMENTED** [review]
Saw this incidentally: You must make sure that the three of you are members of the moia-oss GitHub organization. (That's not the case, thus the squiggly lines under your names.)

**Comment by saeltz** [comment]
And @joroKr21 made a lot of changes. Even though he doesn't work at MOIA anymore, I think he could still be a maintainer if he still wants to contribute.

**Comment by saeltz** [comment]
And while you're at it, please take a look why the Merge Me action fails and close the open dependency updates.

**Comment by houcros** [comment]
> Saw this incidentally: You must make sure that the three of you are members of the moia-oss GitHub organization. (That's not the case, thus the squiggly lines under your names.)

Michael told me, we requested access in the OSS Slack channel :)

> And @joroKr21 made a lot of changes. Even though he doesn't work at MOIA anymore, I think he could still be a maintainer if he still wants to contribute.

We deleted those two handles because of the squiggly red lines under them. We figured since they're not part of the moia-oss group any longer there was no reason to leave "blocked" users there. But we can add them back, sure :)

> And while you're at it, please take a look why the Merge Me action fails and close the open dependency updates.

Yes, that's what triggered this whole thing actually :) We started looking into it today, but were blocked because we can't push nor merge changes here.

**Comment by saeltz** [comment]
Contributors outside of MOIA need to be added individually per project. I just did that for both of them.

**Comment by joroKr21** [comment]
I get this error when I try to accept the invite:

> Sorry, we couldn't find that repository invitation. It is possible that the invitation was revoked or that you are not logged into the invited account.

And it hasn't been 7 days yet so it should still be valid

**Comment by saeltz** [comment]
You should have received a new one a minute ago.

**Comment by joroKr21** [comment]
This time it worked :+1:

**Pull request merged**
